### ISSUE TITLE
How to process user tasks in my own system instead of in the task list?

### ISSUE THREAD

**Issue by Varorbc** [Hafflgav/camunda-8-dotnet-guide#1]
Thank you for your [user guide](https://camunda.com/blog/2022/11/camunda-platform-8-dotnet-developers/). After reading this blog, I have some questions about how to process user tasks in my own system instead of in the task list?

**Comment by Hafflgav** [comment]
Hey @Varorbc!
That's a great question. Apparently this didn't made it into the guide because it is a more advanced topic. 
Camunda Platform 8 offers a [GraphQL API ](https://docs.camunda.io/docs/apis-clients/tasklist-api/tasklist-api-overview/) which can be used to build an individual Tasklist on top. If you do not want to use this API you could possibly consume the event stream from Zeebe. But this adds a whole other complexity. 

A good place for such type of questions is always the [Camunda Forum](https://forum.camunda.io). There are a lot of skilled Camunda folk around and you do not need to wait on my answer. :D 
Hopefully this helped you! :)
